<?php

namespace Database\Seeders;

use App\Models\Publication;
use App\Models\User;
use Illuminate\Database\Seeder;

class PublicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $researchers = User::where('role', 'researcher')->get();

        $publications = [
            [
                'title' => 'CRISPR-Cas9 Mediated Gene Editing: A Comprehensive Review of Applications in Neuroscience',
                'abstract' => 'This review examines the current applications of CRISPR-Cas9 technology in neuroscience research, highlighting recent advances and future prospects.',
                'type' => 'journal_article',
                'journal' => 'Nature Neuroscience',
                'volume' => '45',
                'issue' => '3',
                'pages' => '123-145',
                'publication_year' => 2024,
                'publication_date' => '2024-03-15',
                'doi' => '10.1038/nn.2024.123',
                'pmid' => '38234567',
                'isbn' => null,
                'publisher' => 'Nature Publishing Group',
                'status' => 'published',
                'impact_factor' => 21.126,
                'citations_count' => 15,
                'keywords' => json_encode(['CRISPR-Cas9', 'gene editing', 'neuroscience', 'genetic engineering']),
            ],
            [
                'title' => 'Protein Misfolding in Alzheimer\'s Disease: Mechanisms and Therapeutic Approaches',
                'abstract' => 'Investigation of protein aggregation mechanisms in Alzheimer\'s disease and evaluation of potential therapeutic interventions.',
                'type' => 'journal_article',
                'journal' => 'Cell',
                'volume' => '187',
                'issue' => '12',
                'pages' => '2567-2589',
                'publication_year' => 2024,
                'publication_date' => '2024-02-20',
                'doi' => '10.1016/j.cell.2024.02.015',
                'pmid' => '38123456',
                'isbn' => null,
                'publisher' => 'Cell Press',
                'status' => 'published',
                'impact_factor' => 66.85,
                'citations_count' => 28,
                'keywords' => json_encode(['Alzheimer\'s disease', 'protein folding', 'neurodegeneration', 'therapeutics']),
            ],
            [
                'title' => 'Machine Learning Approaches for Drug Discovery in Oncology',
                'abstract' => 'Comprehensive analysis of machine learning algorithms applied to cancer drug discovery and development.',
                'type' => 'conference_paper',
                'conference' => 'International Conference on Bioinformatics',
                'location' => 'Boston, MA',
                'publication_year' => 2024,
                'publication_date' => '2024-01-10',
                'doi' => '10.1109/ICBI.2024.123',
                'publisher' => 'IEEE',
                'status' => 'published',
                'citations_count' => 12,
                'keywords' => json_encode(['machine learning', 'drug discovery', 'oncology', 'artificial intelligence']),
            ],
            [
                'title' => 'Microbiome Dynamics in Inflammatory Bowel Disease: A Longitudinal Study',
                'abstract' => 'Longitudinal analysis of gut microbiome changes in IBD patients and identification of potential biomarkers.',
                'type' => 'journal_article',
                'journal' => 'Gastroenterology',
                'volume' => '167',
                'issue' => '8',
                'pages' => '1234-1252',
                'publication_year' => 2023,
                'publication_date' => '2023-11-30',
                'doi' => '10.1053/j.gastro.2023.11.015',
                'pmid' => '37987654',
                'publisher' => 'Elsevier',
                'status' => 'published',
                'impact_factor' => 29.85,
                'citations_count' => 22,
                'keywords' => json_encode(['microbiome', 'IBD', 'biomarkers', 'gut health']),
            ],
            [
                'title' => 'Quantum Computing Applications in Biological Systems',
                'abstract' => 'Exploration of quantum computing potential for solving complex biological problems and protein structure prediction.',
                'type' => 'book_chapter',
                'book_title' => 'Advances in Computational Biology',
                'chapter' => '12',
                'pages' => '245-267',
                'publication_year' => 2024,
                'publication_date' => '2024-04-05',
                'isbn' => '978-0-123456-78-9',
                'publisher' => 'Academic Press',
                'editor' => 'Dr. John Smith',
                'status' => 'published',
                'citations_count' => 8,
                'keywords' => json_encode(['quantum computing', 'biology', 'protein structure', 'computational biology']),
            ],
            [
                'title' => 'Nanoparticle-Based Drug Delivery Systems for Cancer Therapy',
                'abstract' => 'Review of current nanoparticle technologies for targeted cancer drug delivery and their clinical applications.',
                'type' => 'journal_article',
                'journal' => 'Nature Reviews Drug Discovery',
                'volume' => '23',
                'issue' => '6',
                'pages' => '456-478',
                'publication_year' => 2024,
                'publication_date' => '2024-05-12',
                'doi' => '10.1038/nrd.2024.067',
                'pmid' => '38567890',
                'publisher' => 'Nature Publishing Group',
                'status' => 'published',
                'impact_factor' => 84.694,
                'citations_count' => 35,
                'keywords' => json_encode(['nanoparticles', 'drug delivery', 'cancer therapy', 'targeted therapy']),
            ],
            [
                'title' => 'Climate Change Impact on Marine Biodiversity: A Global Assessment',
                'abstract' => 'Comprehensive global assessment of climate change effects on marine ecosystems and biodiversity patterns.',
                'type' => 'journal_article',
                'journal' => 'Science',
                'volume' => '384',
                'issue' => '6702',
                'pages' => '1234-1240',
                'publication_year' => 2024,
                'publication_date' => '2024-06-21',
                'doi' => '10.1126/science.adk1234',
                'pmid' => '38901234',
                'publisher' => 'American Association for the Advancement of Science',
                'status' => 'published',
                'impact_factor' => 63.714,
                'citations_count' => 42,
                'keywords' => json_encode(['climate change', 'marine biodiversity', 'global warming', 'ecosystems']),
            ],
            [
                'title' => 'Immunotherapy Advances in Autoimmune Disease Treatment',
                'abstract' => 'Recent developments in immunotherapeutic approaches for treating rheumatoid arthritis and multiple sclerosis.',
                'type' => 'journal_article',
                'journal' => 'The Lancet',
                'volume' => '403',
                'issue' => '10445',
                'pages' => '2123-2135',
                'publication_year' => 2024,
                'publication_date' => '2024-07-15',
                'doi' => '10.1016/S0140-6736(24)01234-5',
                'pmid' => '39012345',
                'publisher' => 'Elsevier',
                'status' => 'published',
                'impact_factor' => 202.731,
                'citations_count' => 18,
                'keywords' => json_encode(['immunotherapy', 'autoimmune diseases', 'rheumatoid arthritis', 'multiple sclerosis']),
            ],
            [
                'title' => 'Synthetic Biology for Sustainable Biofuel Production',
                'abstract' => 'Engineering approaches for developing microorganisms capable of efficient biofuel production from renewable sources.',
                'type' => 'conference_paper',
                'conference' => 'International Synthetic Biology Conference',
                'location' => 'San Francisco, CA',
                'publication_year' => 2023,
                'publication_date' => '2023-10-08',
                'doi' => '10.1109/ISBC.2023.456',
                'publisher' => 'IEEE',
                'status' => 'published',
                'citations_count' => 14,
                'keywords' => json_encode(['synthetic biology', 'biofuels', 'sustainability', 'biotechnology']),
            ],
            [
                'title' => 'Epigenetic Mechanisms in Cancer Development and Progression',
                'abstract' => 'Comprehensive analysis of epigenetic modifications and their regulatory roles in cancer initiation and metastasis.',
                'type' => 'journal_article',
                'journal' => 'Nature Reviews Cancer',
                'volume' => '24',
                'issue' => '4',
                'pages' => '234-256',
                'publication_year' => 2024,
                'publication_date' => '2024-08-03',
                'doi' => '10.1038/nrc.2024.045',
                'pmid' => '39123456',
                'publisher' => 'Nature Publishing Group',
                'status' => 'published',
                'impact_factor' => 69.8,
                'citations_count' => 31,
                'keywords' => json_encode(['epigenetics', 'cancer', 'gene regulation', 'chromatin']),
            ],
            [
                'title' => 'Agricultural Biotechnology: Enhancing Crop Resilience Through Genetic Engineering',
                'abstract' => 'Development and evaluation of genetically modified crops with enhanced resistance to environmental stresses.',
                'type' => 'journal_article',
                'journal' => 'Plant Biotechnology Journal',
                'volume' => '22',
                'issue' => '9',
                'pages' => '1789-1805',
                'publication_year' => 2024,
                'publication_date' => '2024-09-12',
                'doi' => '10.1111/pbi.14567',
                'pmid' => '39234567',
                'publisher' => 'Wiley',
                'status' => 'published',
                'impact_factor' => 13.263,
                'citations_count' => 19,
                'keywords' => json_encode(['agricultural biotechnology', 'genetic engineering', 'crop improvement', 'stress resistance']),
            ],
            [
                'title' => 'Stem Cell Therapy for Neurological Disorders: Current Progress and Future Directions',
                'abstract' => 'Review of stem cell therapeutic approaches for treating spinal cord injuries and neurodegenerative diseases.',
                'type' => 'journal_article',
                'journal' => 'Cell Stem Cell',
                'volume' => '34',
                'issue' => '7',
                'pages' => '923-941',
                'publication_year' => 2023,
                'publication_date' => '2023-12-07',
                'doi' => '10.1016/j.stem.2023.11.008',
                'pmid' => '38012345',
                'publisher' => 'Cell Press',
                'status' => 'published',
                'impact_factor' => 23.9,
                'citations_count' => 26,
                'keywords' => json_encode(['stem cell therapy', 'neurological disorders', 'spinal cord injury', 'regenerative medicine']),
            ],
        ];

        foreach ($publications as $index => $pubData) {
            $correspondingAuthor = $researchers->random();

            Publication::create([
                'title' => $pubData['title'],
                'abstract' => $pubData['abstract'],
                'type' => $pubData['type'],
                'journal' => $pubData['journal'] ?? null,
                'conference' => $pubData['conference'] ?? null,
                'book_title' => $pubData['book_title'] ?? null,
                'volume' => $pubData['volume'] ?? null,
                'issue' => $pubData['issue'] ?? null,
                'chapter' => $pubData['chapter'] ?? null,
                'pages' => $pubData['pages'] ?? null,
                'publication_year' => $pubData['publication_year'],
                'publication_date' => $pubData['publication_date'],
                'doi' => $pubData['doi'] ?? null,
                'pmid' => $pubData['pmid'] ?? null,
                'isbn' => $pubData['isbn'] ?? null,
                'publisher' => $pubData['publisher'] ?? null,
                'editor' => $pubData['editor'] ?? null,
                'location' => $pubData['location'] ?? null,
                'status' => $pubData['status'],
                'impact_factor' => $pubData['impact_factor'] ?? null,
                'citations_count' => $pubData['citations_count'] ?? 0,
                'keywords' => $pubData['keywords'],
                'corresponding_author_id' => $correspondingAuthor->id,
                'peer_reviewed' => in_array($pubData['type'], ['journal_article']),
                'open_access' => rand(0, 1) === 1,
                'language' => 'en',
                'notes' => 'Generated publication for testing purposes.',
            ]);
        }
    }
}