<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $equipment = [
            [
                'name' => 'Olympus BX53 Fluorescence Microscope',
                'model' => 'BX53',
                'serial_number' => 'OLY-BX53-2024-001',
                'category' => 'microscopy',
                'description' => 'Advanced fluorescence microscope with motorized stage and digital camera for high-resolution imaging.',
                'location' => 'Lab Room 201A',
                'status' => 'operational',
                'purchase_date' => '2024-01-15',
                'purchase_price' => 125000.00,
                'supplier' => 'Olympus Scientific Solutions',
                'warranty_expiry' => '2027-01-15',
                'maintenance_interval' => 90,
                'next_maintenance' => '2024-12-15',
                'usage_instructions' => 'Always ensure proper safety protocols. Clean objectives after use. Record usage in logbook.',
            ],
            [
                'name' => 'Thermo Scientific TSQ Fortis GC-MS',
                'model' => 'TSQ Fortis',
                'serial_number' => 'TFS-TSQ-2024-002',
                'category' => 'analytical',
                'description' => 'Triple quadrupole gas chromatography-mass spectrometer for quantitative analysis.',
                'location' => 'Analytical Lab B',
                'status' => 'operational',
                'purchase_date' => '2023-11-20',
                'purchase_price' => 285000.00,
                'supplier' => 'Thermo Fisher Scientific',
                'warranty_expiry' => '2026-11-20',
                'maintenance_interval' => 60,
                'next_maintenance' => '2024-11-20',
                'usage_instructions' => 'Requires specialized training. Check gas pressures before operation. Follow SOPs strictly.',
            ],
            [
                'name' => 'Shimadzu UV-2600i Spectrophotometer',
                'model' => 'UV-2600i',
                'serial_number' => 'SHI-UV26-2024-003',
                'category' => 'spectroscopy',
                'description' => 'High-performance UV-Vis spectrophotometer with integrating sphere attachment.',
                'location' => 'Spectroscopy Lab',
                'status' => 'operational',
                'purchase_date' => '2024-02-10',
                'purchase_price' => 45000.00,
                'supplier' => 'Shimadzu Scientific Instruments',
                'warranty_expiry' => '2027-02-10',
                'maintenance_interval' => 120,
                'next_maintenance' => '2025-02-10',
                'usage_instructions' => 'Warm up for 30 minutes before use. Use appropriate cuvettes. Clean thoroughly after use.',
            ],
            [
                'name' => 'Agilent 1290 Infinity II HPLC System',
                'model' => '1290 Infinity II',
                'serial_number' => 'AGL-1290-2024-004',
                'category' => 'chromatography',
                'description' => 'Ultra-high-performance liquid chromatography system for pharmaceutical analysis.',
                'location' => 'Chromatography Lab',
                'status' => 'operational',
                'purchase_date' => '2023-09-05',
                'purchase_price' => 195000.00,
                'supplier' => 'Agilent Technologies',
                'warranty_expiry' => '2026-09-05',
                'maintenance_interval' => 45,
                'next_maintenance' => '2024-10-15',
                'usage_instructions' => 'Prime system before use. Monitor pressure limits. Use HPLC-grade solvents only.',
            ],
            [
                'name' => 'Class II Biological Safety Cabinet',
                'model' => 'BSC-A2',
                'serial_number' => 'BSC-A2-2024-005',
                'category' => 'safety',
                'description' => 'HEPA-filtered biological safety cabinet for sterile work with biological materials.',
                'location' => 'Microbiology Lab',
                'status' => 'operational',
                'purchase_date' => '2024-03-12',
                'purchase_price' => 12000.00,
                'supplier' => 'Laboratory Safety Solutions',
                'warranty_expiry' => '2027-03-12',
                'maintenance_interval' => 365,
                'next_maintenance' => '2025-03-12',
                'usage_instructions' => 'UV sterilize before and after use. Keep airflow unobstructed. Annual certification required.',
            ],
            [
                'name' => 'Beckman Coulter Optima XPN-100 Ultracentrifuge',
                'model' => 'Optima XPN-100',
                'serial_number' => 'BCK-XPN-2024-006',
                'category' => 'general',
                'description' => 'High-speed ultracentrifuge for protein purification and molecular biology applications.',
                'location' => 'Protein Lab',
                'status' => 'operational',
                'purchase_date' => '2023-12-08',
                'purchase_price' => 165000.00,
                'supplier' => 'Beckman Coulter Life Sciences',
                'warranty_expiry' => '2026-12-08',
                'maintenance_interval' => 180,
                'next_maintenance' => '2024-11-08',
                'usage_instructions' => 'Balance rotors carefully. Check vacuum before operation. Requires training certification.',
            ],
            [
                'name' => 'Zeiss LSM 880 Confocal Microscope',
                'model' => 'LSM 880',
                'serial_number' => 'ZEI-LSM-2024-007',
                'category' => 'microscopy',
                'description' => 'Advanced confocal laser scanning microscope with spectral detection capabilities.',
                'location' => 'Imaging Core Facility',
                'status' => 'operational',
                'purchase_date' => '2024-01-25',
                'purchase_price' => 450000.00,
                'supplier' => 'Carl Zeiss Microscopy',
                'warranty_expiry' => '2027-01-25',
                'maintenance_interval' => 90,
                'next_maintenance' => '2024-12-25',
                'usage_instructions' => 'Book in advance. Laser safety protocols mandatory. Clean objectives with lens paper only.',
            ],
            [
                'name' => 'Bio-Rad ChemiDoc XRS+ Imaging System',
                'model' => 'ChemiDoc XRS+',
                'serial_number' => 'BRD-CDC-2024-008',
                'category' => 'analytical',
                'description' => 'Gel documentation and Western blot imaging system with chemiluminescence detection.',
                'location' => 'Molecular Biology Lab',
                'status' => 'operational',
                'purchase_date' => '2024-04-18',
                'purchase_price' => 35000.00,
                'supplier' => 'Bio-Rad Laboratories',
                'warranty_expiry' => '2027-04-18',
                'maintenance_interval' => 180,
                'next_maintenance' => '2025-04-18',
                'usage_instructions' => 'Keep camera sensor clean. Use appropriate filters. Document settings for reproducibility.',
            ],
            [
                'name' => 'PerkinElmer FTIR Spectrum Two',
                'model' => 'Spectrum Two',
                'serial_number' => 'PKE-FT2-2024-009',
                'category' => 'spectroscopy',
                'description' => 'Fourier-transform infrared spectrometer for chemical identification and analysis.',
                'location' => 'Chemistry Lab',
                'status' => 'maintenance',
                'purchase_date' => '2023-08-15',
                'purchase_price' => 28000.00,
                'supplier' => 'PerkinElmer Inc.',
                'warranty_expiry' => '2026-08-15',
                'maintenance_interval' => 120,
                'next_maintenance' => '2024-10-01',
                'usage_instructions' => 'Clean sampling accessory between samples. Check detector sensitivity. Store in dry environment.',
            ],
            [
                'name' => 'Waters ACQUITY UPLC System',
                'model' => 'ACQUITY H-Class',
                'serial_number' => 'WAT-ACQ-2024-010',
                'category' => 'chromatography',
                'description' => 'Ultra-performance liquid chromatography system for high-resolution separations.',
                'location' => 'Analytical Lab A',
                'status' => 'operational',
                'purchase_date' => '2024-05-22',
                'purchase_price' => 155000.00,
                'supplier' => 'Waters Corporation',
                'warranty_expiry' => '2027-05-22',
                'maintenance_interval' => 60,
                'next_maintenance' => '2024-11-22',
                'usage_instructions' => 'Use sub-2μm particles columns. Monitor back pressure. Prime system thoroughly.',
            ],
            [
                'name' => 'Leica EM UC7 Ultramicrotome',
                'model' => 'EM UC7',
                'serial_number' => 'LEI-UC7-2024-011',
                'category' => 'microscopy',
                'description' => 'Precision ultramicrotome for preparing ultra-thin sections for electron microscopy.',
                'location' => 'Electron Microscopy Facility',
                'status' => 'operational',
                'purchase_date' => '2023-10-30',
                'purchase_price' => 95000.00,
                'supplier' => 'Leica Microsystems',
                'warranty_expiry' => '2026-10-30',
                'maintenance_interval' => 180,
                'next_maintenance' => '2025-01-30',
                'usage_instructions' => 'Keep knives sharp. Control temperature and humidity. Regular cleaning of feed mechanism.',
            ],
            [
                'name' => 'Thermo Heraeus Megafuge 40R Centrifuge',
                'model' => 'Megafuge 40R',
                'serial_number' => 'THR-MF40-2024-012',
                'category' => 'general',
                'description' => 'High-capacity refrigerated centrifuge for large volume sample processing.',
                'location' => 'Central Prep Room',
                'status' => 'operational',
                'purchase_date' => '2024-06-10',
                'purchase_price' => 25000.00,
                'supplier' => 'Thermo Fisher Scientific',
                'warranty_expiry' => '2027-06-10',
                'maintenance_interval' => 365,
                'next_maintenance' => '2025-06-10',
                'usage_instructions' => 'Balance loads properly. Check rotor condition. Regular cleaning and lubrication.',
            ],
            [
                'name' => 'Emergency Eyewash Station',
                'model' => 'ES-200',
                'serial_number' => 'EWS-ES2-2024-013',
                'category' => 'safety',
                'description' => 'ANSI-compliant emergency eyewash and shower station for chemical exposure incidents.',
                'location' => 'Chemistry Lab Corridor',
                'status' => 'operational',
                'purchase_date' => '2024-02-28',
                'purchase_price' => 3500.00,
                'supplier' => 'Safety Equipment Corp',
                'warranty_expiry' => '2029-02-28',
                'maintenance_interval' => 30,
                'next_maintenance' => '2024-10-28',
                'usage_instructions' => 'Test weekly. Keep area clear. Check water temperature and flow rate monthly.',
            ],
            [
                'name' => 'Bruker AVANCE NEO 400 NMR Spectrometer',
                'model' => 'AVANCE NEO 400',
                'serial_number' => 'BRK-AN4-2024-014',
                'category' => 'spectroscopy',
                'description' => '400 MHz NMR spectrometer for structural analysis of organic and inorganic compounds.',
                'location' => 'NMR Facility',
                'status' => 'out_of_order',
                'purchase_date' => '2023-07-12',
                'purchase_price' => 750000.00,
                'supplier' => 'Bruker Corporation',
                'warranty_expiry' => '2026-07-12',
                'maintenance_interval' => 90,
                'next_maintenance' => '2024-09-12',
                'usage_instructions' => 'Liquid helium and nitrogen required. Magnetic field always on. Specialized training mandatory.',
            ],
            [
                'name' => 'Applied Biosystems 3500 Genetic Analyzer',
                'model' => '3500 Genetic Analyzer',
                'serial_number' => 'ABI-3500-2024-015',
                'category' => 'analytical',
                'description' => 'Capillary electrophoresis system for DNA sequencing and fragment analysis.',
                'location' => 'Genomics Lab',
                'status' => 'operational',
                'purchase_date' => '2024-03-08',
                'purchase_price' => 185000.00,
                'supplier' => 'Applied Biosystems',
                'warranty_expiry' => '2027-03-08',
                'maintenance_interval' => 120,
                'next_maintenance' => '2025-03-08',
                'usage_instructions' => 'Change polymer regularly. Clean capillaries weekly. Use polymer without bubbles.',
            ],
        ];

        foreach ($equipment as $equipData) {
            Equipment::create($equipData);
        }
    }
}