<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use Illuminate\Database\Seeder;

class SystemSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings for LIMOSE Lab
            [
                'key' => 'app_name',
                'value' => 'Laboratoire LIMOSE',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Nom du laboratoire',
                'description' => 'Nom du laboratoire affiché dans le système',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'app_description',
                'value' => 'Système de Gestion du Laboratoire LIMOSE - Université de Boumerdès',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Description du laboratoire',
                'description' => 'Description du laboratoire',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'university_name',
                'value' => 'Université M\'Hamed Bougara de Boumerdès',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Nom de l\'université',
                'description' => 'Nom complet de l\'université',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'default_language',
                'value' => 'fr',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Langue par défaut',
                'description' => 'Langue par défaut (ar, fr, en)',
                'is_public' => true,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'in:ar,fr,en']),
                'sort_order' => 4,
            ],

            // Logo Settings
            [
                'key' => 'site_logo',
                'value' => '/images/logos/limose-logo.png',
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Logo principal',
                'description' => 'Logo principal du laboratoire',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'university_logo',
                'value' => '/images/logos/umbb-logo.png',
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Logo de l\'université',
                'description' => 'Logo de l\'université',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'footer_logo',
                'value' => '/images/logos/limose-footer.png',
                'type' => 'image',
                'group' => 'branding',
                'label' => 'Logo pied de page',
                'description' => 'Logo pour le pied de page',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 3,
            ],

            // Contact Information
            [
                'key' => 'contact_email',
                'value' => 'contact@limose.univ-boumerdes.dz',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Email de contact',
                'description' => 'Email de contact principal',
                'is_public' => true,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'email']),
                'sort_order' => 1,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+213-24-81-70-00',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Téléphone de contact',
                'description' => 'Téléphone de contact',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'contact_address',
                'value' => 'Avenue de l\'Indépendance, Boumerdès 35000, Algérie',
                'type' => 'text',
                'group' => 'contact',
                'label' => 'Adresse du laboratoire',
                'description' => 'Adresse physique du laboratoire',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'timezone',
                'value' => 'Africa/Algiers',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Fuseau horaire',
                'description' => 'Fuseau horaire par défaut du système',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'string']),
                'sort_order' => 5,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Mode maintenance',
                'description' => 'Activer le mode maintenance pour empêcher l\'accès des utilisateurs',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 6,
            ],

            // User Management Settings
            [
                'key' => 'allow_user_registration',
                'value' => 'false',
                'type' => 'boolean',
                'group' => 'users',
                'label' => 'Autoriser l\'inscription',
                'description' => 'Permettre aux nouveaux utilisateurs de s\'inscrire',
                'is_public' => true,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'require_email_verification',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'users',
                'label' => 'Vérification email requise',
                'description' => 'Exiger la vérification de l\'email pour les nouveaux comptes',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'group' => 'users',
                'label' => 'Longueur minimale mot de passe',
                'description' => 'Longueur minimale requise pour le mot de passe',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:6', 'max:50']),
                'sort_order' => 3,
            ],
            [
                'key' => 'session_timeout',
                'value' => '120',
                'type' => 'integer',
                'group' => 'users',
                'label' => 'Expiration session (minutes)',
                'description' => 'Délai d\'expiration de session utilisateur en minutes',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:15', 'max:480']),
                'sort_order' => 4,
            ],

            // Email Settings
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@limose.univ-boumerdes.dz',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Adresse email expéditeur',
                'description' => 'Adresse email par défaut de l\'expéditeur',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'email']),
                'sort_order' => 1,
            ],
            [
                'key' => 'mail_from_name',
                'value' => 'Système LIMOSE',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Nom expéditeur',
                'description' => 'Nom par défaut de l\'expéditeur',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'notification_email_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'email',
                'label' => 'Notifications email activées',
                'description' => 'Envoyer des notifications par email aux utilisateurs',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 3,
            ],

            // Equipment Settings
            [
                'key' => 'equipment_booking_advance_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'equipment',
                'label' => 'Jours de réservation à l\'avance',
                'description' => 'Nombre maximum de jours à l\'avance pour réserver un équipement',
                'is_public' => true,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:365']),
                'sort_order' => 1,
            ],
            [
                'key' => 'equipment_max_booking_duration',
                'value' => '8',
                'type' => 'integer',
                'group' => 'equipment',
                'label' => 'Durée max réservation (heures)',
                'description' => 'Durée maximale de réservation d\'équipement en heures',
                'is_public' => true,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:24']),
                'sort_order' => 2,
            ],
            [
                'key' => 'equipment_maintenance_reminder_days',
                'value' => '7',
                'type' => 'integer',
                'group' => 'equipment',
                'label' => 'Rappel maintenance (jours)',
                'description' => 'Jours avant échéance maintenance pour envoyer un rappel',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:30']),
                'sort_order' => 3,
            ],

            // Project Settings
            [
                'key' => 'project_default_duration_months',
                'value' => '12',
                'type' => 'integer',
                'group' => 'projects',
                'label' => 'Durée projet par défaut (mois)',
                'description' => 'Durée par défaut pour les nouveaux projets en mois',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:60']),
                'sort_order' => 1,
            ],
            [
                'key' => 'project_budget_currency',
                'value' => 'DZD',
                'type' => 'string',
                'group' => 'projects',
                'label' => 'Devise par défaut',
                'description' => 'Devise par défaut pour les budgets de projet',
                'is_public' => true,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'string', 'size:3']),
                'sort_order' => 2,
            ],

            // File Upload Settings
            [
                'key' => 'max_file_upload_size',
                'value' => '10240',
                'type' => 'integer',
                'group' => 'uploads',
                'label' => 'Taille max fichier (KB)',
                'description' => 'Taille maximale de fichier téléchargeable en kilooctets',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1024', 'max:102400']),
                'sort_order' => 1,
            ],
            [
                'key' => 'allowed_file_types',
                'value' => 'pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif',
                'type' => 'string',
                'group' => 'uploads',
                'label' => 'Types de fichiers autorisés',
                'description' => 'Liste séparée par virgules des extensions de fichiers autorisées',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 2,
            ],

            // Notification Settings
            [
                'key' => 'notifications_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'notifications',
                'label' => 'Notifications activées',
                'description' => 'Activer les notifications système',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'notification_retention_days',
                'value' => '90',
                'type' => 'integer',
                'group' => 'notifications',
                'label' => 'Rétention notifications (jours)',
                'description' => 'Jours de conservation des notifications avant nettoyage automatique',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:7', 'max:365']),
                'sort_order' => 2,
            ],

            // Security Settings
            [
                'key' => 'max_login_attempts',
                'value' => '5',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Tentatives connexion max',
                'description' => 'Nombre maximum de tentatives de connexion échouées avant verrouillage',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:3', 'max:10']),
                'sort_order' => 1,
            ],
            [
                'key' => 'lockout_duration_minutes',
                'value' => '15',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Durée verrouillage (minutes)',
                'description' => 'Durée de verrouillage du compte en minutes',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:5', 'max:60']),
                'sort_order' => 2,
            ],
            [
                'key' => 'force_https',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Forcer HTTPS',
                'description' => 'Forcer HTTPS pour toutes les connexions',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 3,
            ],

            // Backup Settings
            [
                'key' => 'backup_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'group' => 'backup',
                'label' => 'Sauvegardes automatiques',
                'description' => 'Activer les sauvegardes automatiques de base de données',
                'is_public' => false,
                'is_editable' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'backup_frequency_hours',
                'value' => '24',
                'type' => 'integer',
                'group' => 'backup',
                'label' => 'Fréquence sauvegarde (heures)',
                'description' => 'Fréquence de sauvegarde en heures',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:1', 'max:168']),
                'sort_order' => 2,
            ],
            [
                'key' => 'backup_retention_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'backup',
                'label' => 'Rétention sauvegardes (jours)',
                'description' => 'Jours de conservation des fichiers de sauvegarde',
                'is_public' => false,
                'is_editable' => true,
                'validation_rules' => json_encode(['required', 'integer', 'min:7', 'max:365']),
                'sort_order' => 3,
            ],
        ];

        foreach ($settings as $setting) {
            SystemSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}